# Generated by Django 4.1.3 on 2022-12-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='工号')),
                ('birth_date', models.DateTimeField(verbose_name='生日')),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('hire_date', models.DateTimeField(verbose_name='入职时间')),
            ],
            options={
                'verbose_name': '员工',
                'db_table': 'employee',
            },
        ),
    ]
